version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - aws s3 sync dist/ s3://your-s3-bucket-name/

post_build:
  commands:
    - aws cloudfront create-invalidation --distribution-id your-cloudfront-distribution-id --paths "/*"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/
