version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 sync dist/ s3://bucketbforfrontmain
      - aws cloudfront create-invalidation --distribution-id E2X4DJ459H6IN --paths "/*"
post_build:
  commands:
    - aws cloudfront create-invalidation --distribution-id E2X4DJ459H6IN --paths "/*"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/
