version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  pre_build:
    commands:
      # Install n package manager
      - npm install -g n

  build:
    commands:
      # Update Node.js version to 14
      - n 14
  build:
    commands:
      - npm run build
      - aws s3 sync dist/ s3://frontmain-frontmainartifactsbucket879156a5-1cxflqqjchjnd
post_build:
  commands:
    - aws cloudfront create-invalidation --distribution-id EK8PDLNVW7CQU --paths "/*"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/
