version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - aws s3 sync dist/ s3://frontinframain-bucketforfrontendmain1c67891b-10h4q1ll9k74j

post_build:
  commands:
    - aws cloudfront create-invalidation --distribution-id EK8PDLNVW7CQU --paths "/*"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/
